spring:
  config:
    import: optional:file:.env

  application:
    name: myKart

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:Test}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: true
    database: POSTGRESQL

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT:8089}

  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/kart-service}

logging:
  level:
    com.building.mykart: DEBUG
#    root: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
#    org.hibernate.SQL: DEBUG
