-- MyKart database schema
-- Runs on first Postgres startup when mounted to /docker-entrypoint-initdb.d/
-- Matches JPA entities (GenerationType.IDENTITY). Re-run requires: docker compose down -v

CREATE TABLE tbl_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255),
    username        VARCHAR(255),
    email           VARCHAR(255),
    password        VARCHAR(255),
    type            VARCHAR(255),
    address         VARCHAR(255),
    CONSTRAINT tbl_user_type_check CHECK (type IN ('SELLER', 'BUYER'))
);

INSERT INTO tbl_user (address, email, name, password, type, username) 
VALUES ('Kolkata', 'rg6035656@gmail.com', 'Rahul Gupta', '$2a$10$23kDu5bkCJzfME6MYXHsfu8O7/Wg8FyB6.TPYeo10VWw4zRLsGJPe', 'SELLER', 'rahulgupta');

CREATE TABLE item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    price           DECIMAL(18, 4) NOT NULL,
    weight          DECIMAL(10, 2),
    seller_id       BIGINT,
    CONSTRAINT fk_item_seller
        FOREIGN KEY (seller_id) REFERENCES tbl_user (id)
);

CREATE TABLE kart (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    items           JSONB,
    user_id         BIGINT NOT NULL,
    CONSTRAINT fk_kart_user
        FOREIGN KEY (user_id) REFERENCES tbl_user (id)
);

CREATE TABLE orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    total_amount        DECIMAL(18, 4) NOT NULL,
    status              VARCHAR(50) NOT NULL,
    shipping_address    VARCHAR(255),
    created_on          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES tbl_user (id),
    CONSTRAINT chk_order_status
        CHECK (status IN ('CREATED', 'PLACED', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED'))
);

CREATE TABLE order_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL,
    item_id         BIGINT NOT NULL,
    quantity        INTEGER NOT NULL,
    price           DECIMAL(18, 4) NOT NULL,
    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_item_item
        FOREIGN KEY (item_id) REFERENCES item (id),
    CONSTRAINT chk_order_item_quantity
        CHECK (quantity > 0),
    CONSTRAINT uk_order_item_order_item
        UNIQUE (order_id, item_id)
);

CREATE INDEX idx_item_seller_id ON item (seller_id);
CREATE INDEX idx_kart_user_id ON kart (user_id);
CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE INDEX idx_order_item_order_id ON order_item (order_id);

-- Optional dev seed (password for both users: password)
-- INSERT INTO tbl_user (name, username, email, password, type, address) VALUES
--     ('Seller One', 'seller1', 'seller1@example.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'SELLER', '123 Seller St'),
--     ('Buyer One', 'buyer1', 'buyer1@example.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'BUYER', '456 Buyer Ave');
--
-- INSERT INTO item (name, price, weight, seller_id) VALUES
--     ('Widget', 19.9900, 0.50, 1),
--     ('Gadget', 49.9900, 1.20, 1);
