CREATE TABLE item (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(18,4) NOT NULL,
    weight DECIMAL(10,2),
    seller_id BIGINT,
    CONSTRAINT fk_item_seller
        FOREIGN KEY (seller_id)
        REFERENCES tbl_user(id)
);

CREATE TABLE kart (
    id BIGINT PRIMARY KEY,
	items JSONB,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES tbl_user(id)
);

CREATE TABLE tbl_user (
    id bigint PRIMARY KEY,
    address VARCHAR(255),
    email VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    type VARCHAR(255),
    username VARCHAR(255),
    CONSTRAINT tbl_user_pkey PRIMARY KEY (id),
    CONSTRAINT tbl_user_type_check CHECK (type::text = ANY (ARRAY['SELLER'::character varying, 'BUYER'::character varying]::text[]))
);

CREATE SEQUENCE item_id_seq START 1;
ALTER TABLE item ALTER COLUMN id SET DEFAULT nextval('item_id_seq');

CREATE SEQUENCE kart_id_seq START 1;
ALTER TABLE kart ALTER COLUMN id SET DEFAULT nextval('kart_id_seq');

CREATE SEQUENCE tbl_user_id_seq START 1;
ALTER TABLE tbl_user ALTER COLUMN id SET DEFAULT nextval('tbl_user_id_seq');

CREATE TABLE orders (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    total_amount DECIMAL(18,4) NOT NULL,
    status VARCHAR(50) NOT NULL,
    shipping_address VARCHAR(255),
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id)
        REFERENCES tbl_user(id),
    CONSTRAINT chk_order_status
        CHECK (
            status IN
            (
                'CREATED',
                'PLACED',
                'PAID',
                'SHIPPED',
                'DELIVERED',
                'CANCELLED'
            )
        )
);

CREATE TABLE order_item (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    price DECIMAL(18,4) NOT NULL,
    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_order_item_item
        FOREIGN KEY (item_id)
        REFERENCES item(id),
    CONSTRAINT chk_order_item_quantity
        CHECK (quantity > 0),
    CONSTRAINT uk_order_item_order_item
        UNIQUE (order_id, item_id)
);

-- ---------------------------------------------------------------------------
-- Fix existing DB (run once if checkout fails: null value in column "id")
-- Hibernate expects IDENTITY columns; plain BIGINT + separate sequence is not enough.
-- ---------------------------------------------------------------------------
-- ALTER TABLE orders ALTER COLUMN id DROP DEFAULT;
-- DROP SEQUENCE IF EXISTS orders_id_seq;
-- ALTER TABLE orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
--
-- ALTER TABLE order_item ALTER COLUMN id DROP DEFAULT;
-- DROP SEQUENCE IF EXISTS order_item_id_seq;
-- ALTER TABLE order_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
